### ISSUE TITLE
uncompressed source for simple-dropdown-item

### ISSUE THREAD

**Issue by ShaggyDude** [SimpleElements/simple-dropdown#1]
Do you have the uncompressed source for simple-dropdown-item?

**Comment by seaneking** [comment]
Whoops! `simple-dropdown-item.html` is long deprecated/unused, it's left over from the original buildstep. Can't believe I didn't spot it before.

I'll remove it now, and do a major bump. Thanks for flagging.

**Comment by ShaggyDude** [comment]
cool
